spring:
  application:
    name: nacos-discovery-a
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    inetutils:
      preferred-networks: 192.168.31

server:
  port: 8081
